/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northdownnets2;

import BaseData.Customer;
import BaseData.CustomerList;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author DevUser
 */
public class DetailsForm extends javax.swing.JFrame {

    public CustomerList custList;
    public Customer thisCustomer;

    public DetailsForm(Customer c) {
        initComponents();
        
       
        thisCustomer = c;
        custList = new CustomerList();
        setTextInfo();
        checkForGuest();
    }

    //This method converts the java.util.sql to a java.util.date so that it can be added to the MS Access database
    private java.util.Date convertSqlToUtilDate(java.sql.Date sqlDate) {
        return new java.util.Date(sqlDate.getTime());
    }

    public void setTextInfo() {
        //Each text field is populated with the users information from the database
        txtUpdateUsername.setText(thisCustomer.getUsername());
        txtUpdatePassword.setText(thisCustomer.getPassword());
        txtUpdateFirstname.setText(thisCustomer.getFirstname());
        txtUpdateLastname.setText(thisCustomer.getLastname());
        txtUpdateDateOfBirth.setValue(thisCustomer.getDateOfBirth());
        txtUpdateEmail.setText(thisCustomer.getEmail());
        txtUpdatePhoneNumber.setText(thisCustomer.getPhoneNumber());
        txtUpdateSecurityQuestion.setText(thisCustomer.getSecurityQuestion());
        txtUpdateSecurityAnswer.setText(thisCustomer.getSecurityAnswer());
    }
    
    public void checkForGuest() {
        //If the user is a guest then they can not amend their information
        //All text fields are set to unEditable
        if (txtUpdateUsername.getText().equals("guest"))
            {
                btnUpdate.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Cannot amend information if signed in as a guest.");
                txtUpdateUsername.setEditable(false);
                txtUpdatePassword.setEditable(false);
                txtUpdateFirstname.setEditable(false);
                txtUpdateLastname.setEditable(false);
                txtUpdateDateOfBirth.setEditable(false);
                txtUpdateEmail.setEditable(false);
                txtUpdatePhoneNumber.setEditable(false);
                txtUpdateSecurityQuestion.setEditable(false);
                txtUpdateSecurityAnswer.setEditable(false);
            }
    }
    
    public void updateInfo() {
        //The amended user information is updated if validation checks are adhered to
        thisCustomer.setUsername(txtUpdateUsername.getText());
        thisCustomer.setPassword(txtUpdatePassword.getText());
        thisCustomer.setFirstname(txtUpdateFirstname.getText());
        thisCustomer.setLastname(txtUpdateLastname.getText());
        thisCustomer.setDateOfBirth((java.util.Date) txtUpdateDateOfBirth.getValue());
        thisCustomer.setEmail(txtUpdateEmail.getText());
        thisCustomer.setPhoneNumber(txtUpdatePhoneNumber.getText());
        thisCustomer.setSecurityQuestion(txtUpdateSecurityQuestion.getText());
        thisCustomer.setSecurityAnswer(txtUpdateSecurityAnswer.getText());
        
        //The customers details are updated in the database
        custList.updateCustomer(thisCustomer);
        
        //The form is then closed
        this.dispose();
    }
    
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUpdateUsername = new javax.swing.JTextField();
        txtUpdatePassword = new javax.swing.JTextField();
        txtUpdateFirstname = new javax.swing.JTextField();
        txtUpdateLastname = new javax.swing.JTextField();
        txtUpdateEmail = new javax.swing.JTextField();
        txtUpdatePhoneNumber = new javax.swing.JTextField();
        txtUpdateSecurityQuestion = new javax.swing.JTextField();
        txtUpdateSecurityAnswer = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtUpdateDateOfBirth = new javax.swing.JFormattedTextField();
        lblUsernameError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        lblFirstnameError = new javax.swing.JLabel();
        lblLastnameError = new javax.swing.JLabel();
        lblDoBError = new javax.swing.JLabel();
        lblPhoneNoError = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        lblSecurityQuestionError = new javax.swing.JLabel();
        lblSecurityAnswerError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Details Form");

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Firstname:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lastname:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone number:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Security Question:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Security Answer:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtUpdateDateOfBirth.setEditable(false);
        txtUpdateDateOfBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtUpdateDateOfBirth.setText(" ");
        txtUpdateDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateDateOfBirthActionPerformed(evt);
            }
        });

        lblUsernameError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUsernameError.setForeground(new java.awt.Color(255, 255, 255));
        lblUsernameError.setText(" ");

        lblPasswordError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordError.setText(" ");

        lblFirstnameError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFirstnameError.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstnameError.setText(" ");

        lblLastnameError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLastnameError.setForeground(new java.awt.Color(255, 255, 255));
        lblLastnameError.setText(" ");

        lblDoBError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDoBError.setForeground(new java.awt.Color(255, 255, 255));
        lblDoBError.setText(" ");

        lblPhoneNoError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPhoneNoError.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNoError.setText(" ");

        lblEmailError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmailError.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailError.setText(" ");

        lblSecurityQuestionError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSecurityQuestionError.setForeground(new java.awt.Color(255, 255, 255));
        lblSecurityQuestionError.setText(" ");

        lblSecurityAnswerError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSecurityAnswerError.setForeground(new java.awt.Color(255, 255, 255));
        lblSecurityAnswerError.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUpdatePassword)
                    .addComponent(txtUpdateFirstname)
                    .addComponent(txtUpdateLastname)
                    .addComponent(txtUpdateEmail)
                    .addComponent(txtUpdatePhoneNumber)
                    .addComponent(txtUpdateSecurityQuestion)
                    .addComponent(txtUpdateSecurityAnswer)
                    .addComponent(txtUpdateUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUpdateDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(lblUsernameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecurityAnswerError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecurityQuestionError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhoneNoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDoBError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLastnameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFirstnameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUpdateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsernameError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUpdateFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstnameError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUpdateLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastnameError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUpdateDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoBError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUpdateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUpdatePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNoError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtUpdateSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecurityQuestionError))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUpdateSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecurityAnswerError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //This boolean variable ensures data can only be updated if no fields are empty
        boolean emptyFields = false;
        
        //If field is empty emptyFields variable is set to true
        if (txtUpdateUsername.getText().trim().equals("")) {
            lblUsernameError.setText("Username field is empty");
            emptyFields = true;
        }

        if (txtUpdatePassword.getText().trim().equals("")) {
            lblPasswordError.setText("Password field is empty");
            emptyFields = true;
        }

        if (txtUpdateFirstname.getText().trim().equals("")) {
            lblFirstnameError.setText("Firstname field is empty");
            emptyFields = true;
        }

        if (txtUpdateLastname.getText().trim().equals("")) {
            lblLastnameError.setText("Lastname field is empty");
            emptyFields = true;
        }

        if (txtUpdateDateOfBirth.getText().trim().equals("")) {
            lblDoBError.setText("Date Of Birth field is empty");
            //emptyFields = true;
        }

        if (txtUpdatePhoneNumber.getText().trim().equals("")) {
            lblPhoneNoError.setText("Phone Number field is empty");
            emptyFields = true;
        }

        if (txtUpdateEmail.getText().trim().equals("")) {
            lblEmailError.setText("Email field is empty");
            emptyFields = true;
        }

        if (txtUpdateSecurityQuestion.getText().trim().equals("")) {
            lblSecurityQuestionError.setText("Security Question field is empty");
            emptyFields = true;
        }

        if (txtUpdateSecurityAnswer.getText().trim().equals("")) {
            lblSecurityAnswerError.setText("Security Answer field is empty");
            emptyFields = true;

        }

        //This boolean variable ensures data can only be updated if text fields are in the correct format
        boolean validationCheck = false;
        //If text does not adhere to the defined validation the variable validationCheck is set to true
        
        //The text field is converted to a character array so that each individual character can be checked to ensure there are no numbers in the field
        char[] firstnameCheck = txtUpdateFirstname.getText().trim().toCharArray();
        for (int i = 0; i < firstnameCheck.length; i++) {
            if (Character.isDigit(firstnameCheck[i])) {
                JOptionPane.showMessageDialog(null, "Firstname can not contain numbers");
                validationCheck = true;
                break;
            }
        }
        
        //The text field is converted to a character array so that each individual character can be checked to ensure there are no numbers in the field
        char[] lastnameCheck = txtUpdateLastname.getText().trim().toCharArray();
        for (int i = 0; i < lastnameCheck.length; i++) {
            if (Character.isDigit(lastnameCheck[i])) {
                JOptionPane.showMessageDialog(null, "Lastname can not contain numbers");
                validationCheck = true;
                break;
            }
        }
        
        //The text field is converted to a character array to ensure that the length of the field is exactly 11 digits
        char[] phoneNoCheck = txtUpdatePhoneNumber.getText().trim().toCharArray();
        if(phoneNoCheck.length != 11) {
            JOptionPane.showMessageDialog(null, "Phone number must be 11 numbers");
        }
        
        //This character array is also used so that each individual character can be checked to ensure there are no letters in the field
        for (int i = 0; i < phoneNoCheck.length; i++) {
            if(Character.isLetter(phoneNoCheck[i])) {
            JOptionPane.showMessageDialog(null, "Phone number can not contain letters");
            validationCheck = true;
            break;
            }
        }
        
        
        
        //The string regex is used to ensure th email field follows the correct format
        String regex = "^(.+)@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher m = pattern.matcher(txtUpdateEmail.getText().trim());  
        //Matching the particular pattern against regular expression  
        boolean matches = m.matches();  
        if(matches == false){
            JOptionPane.showMessageDialog(null, "Email must follow format: characters + @ + characters + .");
            validationCheck = true;
        }
        
        if (emptyFields == false && validationCheck == false) {
            updateInfo();
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtUpdateDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateDateOfBirthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsForm().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDoBError;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblFirstnameError;
    private javax.swing.JLabel lblLastnameError;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblPhoneNoError;
    private javax.swing.JLabel lblSecurityAnswerError;
    private javax.swing.JLabel lblSecurityQuestionError;
    private javax.swing.JLabel lblUsernameError;
    private javax.swing.JFormattedTextField txtUpdateDateOfBirth;
    private javax.swing.JTextField txtUpdateEmail;
    private javax.swing.JTextField txtUpdateFirstname;
    private javax.swing.JTextField txtUpdateLastname;
    private javax.swing.JTextField txtUpdatePassword;
    private javax.swing.JTextField txtUpdatePhoneNumber;
    private javax.swing.JTextField txtUpdateSecurityAnswer;
    private javax.swing.JTextField txtUpdateSecurityQuestion;
    private javax.swing.JTextField txtUpdateUsername;
    // End of variables declaration//GEN-END:variables
}
