/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northdownnets2;

import BaseData.Customer;
import BaseData.CustomerList;
import javax.swing.*;
import java.io.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author DevUser
 */
public class RegisterForm extends javax.swing.JFrame {

    public CustomerList custList;

    public RegisterForm(CustomerList custList) {
        initComponents();
        this.custList = custList;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm((CustomerList) null).setVisible(true);
            }
        });
    }

    public void insertNewCustomer() {
        //The text in each field is set to its corresponding String so that it can be used in the customer constructor which is then added to the customerList
        int customerID = 0;
        String username = txtUsernameReg.getText().trim();
        String password = txtPasswordReg.getText().trim();
        String firstname = txtFirstnameReg.getText().trim();
        String lastname = txtLastnameReg.getText().trim();
        String email = txtEmailReg.getText().trim();
        Date dateOfBirth = (Date) txtDateOfBirthReg.getValue();
        String phoneNumber = txtPhoneNumberReg.getText().trim();
        String securityQuestion = txtSecurityQuestionReg.getText().trim();
        String securityAnswer = txtSecurityAnswerReg.getText().trim();
        boolean seasonTicket = false;

        Customer customer = new Customer(customerID, username, password, firstname, lastname, dateOfBirth, email, phoneNumber, securityQuestion, securityAnswer, seasonTicket);
        custList.addCustomer(customer);

        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsernameReg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordReg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFirstnameReg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLastnameReg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmailReg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPhoneNumberReg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSecurityQuestionReg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSecurityAnswerReg = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        lblUsernameRegError = new javax.swing.JLabel();
        lblPasswordRegError = new javax.swing.JLabel();
        lblFirstnameRegError = new javax.swing.JLabel();
        lblLastnameRegError = new javax.swing.JLabel();
        lblDoBRegError = new javax.swing.JLabel();
        lblPhoneNoRegError = new javax.swing.JLabel();
        lblEmailRegError = new javax.swing.JLabel();
        lblSecurityQuestionRegError = new javax.swing.JLabel();
        lblSecurityAnswerRegError = new javax.swing.JLabel();
        txtDateOfBirthReg = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome new user, please enter all fields:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");

        txtUsernameReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameRegActionPerformed(evt);
            }
        });
        txtUsernameReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameRegKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        txtPasswordReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordRegKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Firstname:");
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtFirstnameReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstnameRegKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lastname:");

        txtLastnameReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastnameRegKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");

        txtEmailReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailRegKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone number:");

        txtPhoneNumberReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneNumberRegKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Security Question:");

        txtSecurityQuestionReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSecurityQuestionRegKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Security Answer:");

        txtSecurityAnswerReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSecurityAnswerRegKeyPressed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblUsernameRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblUsernameRegError.setText(" ");

        lblPasswordRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordRegError.setText(" ");

        lblFirstnameRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstnameRegError.setText(" ");

        lblLastnameRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblLastnameRegError.setText(" ");

        lblDoBRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblDoBRegError.setText(" ");

        lblPhoneNoRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNoRegError.setText(" ");

        lblEmailRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailRegError.setText(" ");

        lblSecurityQuestionRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblSecurityQuestionRegError.setText(" ");

        lblSecurityAnswerRegError.setForeground(new java.awt.Color(255, 255, 255));
        lblSecurityAnswerRegError.setText(" ");

        txtDateOfBirthReg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDateOfBirthReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateOfBirthRegKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailReg)
                            .addComponent(txtPhoneNumberReg, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtUsernameReg)
                            .addComponent(txtPasswordReg)
                            .addComponent(txtFirstnameReg)
                            .addComponent(txtLastnameReg)
                            .addComponent(txtSecurityQuestionReg)
                            .addComponent(txtSecurityAnswerReg, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(txtDateOfBirthReg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsernameRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPasswordRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFirstnameRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLastnameRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDoBRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhoneNoRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmailRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSecurityQuestionRegError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSecurityAnswerRegError, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsernameRegError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordRegError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFirstnameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstnameRegError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLastnameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastnameRegError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDoBRegError)
                    .addComponent(txtDateOfBirthReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPhoneNumberReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNoRegError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailRegError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSecurityQuestionReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecurityQuestionRegError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSecurityAnswerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecurityAnswerRegError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4AncestorAdded

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        
    //This boolean variable ensures data can only be updated if no fields are empty
        boolean emptyFields = false;
        
        //If field is empty emptyFields variable is set to true
        if (txtUsernameReg.getText().trim().equals("")) {
            lblUsernameRegError.setText("Username field is empty");
            emptyFields = true;
        }

        if (txtPasswordReg.getText().trim().equals("")) {
            lblPasswordRegError.setText("Password field is empty");
            emptyFields = true;
        }

        if (txtFirstnameReg.getText().trim().equals("")) {
            lblFirstnameRegError.setText("Firstname field is empty");
            emptyFields = true;
        }

        if (txtLastnameReg.getText().trim().equals("")) {
            lblLastnameRegError.setText("Lastname field is empty");
            emptyFields = true;
        }

        if (txtDateOfBirthReg.getText().trim().equals("")) {
            lblDoBRegError.setText("Date Of Birth field is empty");
            //emptyFields = true;
        }

        if (txtPhoneNumberReg.getText().trim().equals("")) {
            lblPhoneNoRegError.setText("Phone Number field is empty");
            emptyFields = true;
        }

        if (txtEmailReg.getText().trim().equals("")) {
            lblEmailRegError.setText("Email field is empty");
            emptyFields = true;
        }

        if (txtSecurityQuestionReg.getText().trim().equals("")) {
            lblSecurityQuestionRegError.setText("Security Question field is empty");
            emptyFields = true;
        }

        if (txtSecurityAnswerReg.getText().trim().equals("")) {
            lblSecurityAnswerRegError.setText("Security Answer field is empty");
            emptyFields = true;

        }

        //This boolean variable ensures data can only be updated if text fields are in the correct format
        boolean validationCheck = false;
        //If text does not adhere to the defined validation the variable validationCheck is set to true
        
        //The text field is converted to a character array so that each individual character can be checked to ensure there are no numbers in the field
        char[] firstnameCheck = txtFirstnameReg.getText().toString().trim().toCharArray();
        for (int i = 0; i < firstnameCheck.length; i++) {
            if (Character.isDigit(firstnameCheck[i])) {
                JOptionPane.showMessageDialog(null, "Firstname can not contain numbers");
                validationCheck = true;
                break;
            }
        }

        //The text field is converted to a character array so that each individual character can be checked to ensure there are no numbers in the field
        char[] lastnameCheck = txtLastnameReg.getText().toString().trim().toCharArray();
        for (int i = 0; i < lastnameCheck.length; i++) {
            if (Character.isDigit(lastnameCheck[i])) {
                JOptionPane.showMessageDialog(null, "Lastname can not contain numbers");
                validationCheck = true;
                break;
            }
        }
        
        //The text field is converted to a character array to ensure that the length of the field is exactly 11 digits
        char[] phoneNoCheck = txtPhoneNumberReg.getText().toString().trim().toCharArray();
        if(phoneNoCheck.length != 11) {
            JOptionPane.showMessageDialog(null, "Phone number must be 11 numbers");
        }
        
        //This character array is also used so that each individual character can be checked to ensure there are no letters in the field
        for (int i = 0; i < phoneNoCheck.length; i++) {
            if(Character.isLetter(phoneNoCheck[i])) {
            JOptionPane.showMessageDialog(null, "Phone number can not contain letters");
            validationCheck = true;
            break;
            }
        }
        
        
        
        //The string regex is used to ensure th email field follows the correct format
        String regex = "^(.+)@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher m = pattern.matcher(txtEmailReg.getText().toString().trim());  
        //Matching the particular pattern against regular expression  
        boolean matches = m.matches();  
        if(matches == false){
            JOptionPane.showMessageDialog(null, "Email must follow format: characters + @ + characters + .");
            validationCheck = true;
        }
        

        if (emptyFields == false && validationCheck == false) {
            insertNewCustomer();
        }


    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtUsernameRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameRegActionPerformed

    private void txtUsernameRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameRegKeyPressed
        lblUsernameRegError.setText(" ");
    }//GEN-LAST:event_txtUsernameRegKeyPressed

    private void txtPasswordRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordRegKeyPressed
        lblPasswordRegError.setText(" ");
    }//GEN-LAST:event_txtPasswordRegKeyPressed

    private void txtFirstnameRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameRegKeyPressed
        lblFirstnameRegError.setText(" ");
    }//GEN-LAST:event_txtFirstnameRegKeyPressed

    private void txtLastnameRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameRegKeyPressed
        lblLastnameRegError.setText(" ");
    }//GEN-LAST:event_txtLastnameRegKeyPressed

    private void txtDateOfBirthRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateOfBirthRegKeyPressed
        lblDoBRegError.setText(" ");
    }//GEN-LAST:event_txtDateOfBirthRegKeyPressed

    private void txtPhoneNumberRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberRegKeyPressed
        lblPhoneNoRegError.setText(" ");
    }//GEN-LAST:event_txtPhoneNumberRegKeyPressed

    private void txtEmailRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailRegKeyPressed
        lblEmailRegError.setText(" ");
    }//GEN-LAST:event_txtEmailRegKeyPressed

    private void txtSecurityQuestionRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecurityQuestionRegKeyPressed
        lblSecurityQuestionRegError.setText(" ");
    }//GEN-LAST:event_txtSecurityQuestionRegKeyPressed

    private void txtSecurityAnswerRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecurityAnswerRegKeyPressed
        lblSecurityAnswerRegError.setText(" ");
    }//GEN-LAST:event_txtSecurityAnswerRegKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDoBRegError;
    private javax.swing.JLabel lblEmailRegError;
    private javax.swing.JLabel lblFirstnameRegError;
    private javax.swing.JLabel lblLastnameRegError;
    private javax.swing.JLabel lblPasswordRegError;
    private javax.swing.JLabel lblPhoneNoRegError;
    private javax.swing.JLabel lblSecurityAnswerRegError;
    private javax.swing.JLabel lblSecurityQuestionRegError;
    private javax.swing.JLabel lblUsernameRegError;
    private javax.swing.JFormattedTextField txtDateOfBirthReg;
    private javax.swing.JTextField txtEmailReg;
    private javax.swing.JTextField txtFirstnameReg;
    private javax.swing.JTextField txtLastnameReg;
    private javax.swing.JTextField txtPasswordReg;
    private javax.swing.JTextField txtPhoneNumberReg;
    private javax.swing.JTextField txtSecurityAnswerReg;
    private javax.swing.JTextField txtSecurityQuestionReg;
    private javax.swing.JTextField txtUsernameReg;
    // End of variables declaration//GEN-END:variables
}
